/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedRecipeKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteRecipe"
      | "getEncryptedIngredient"
      | "getRecipe"
      | "getRecipeCount"
      | "getRecipeIngredients"
      | "getRecipeSteps"
      | "getUserRecipeCount"
      | "getUserRecipes"
      | "owner"
      | "pause"
      | "paused"
      | "protocolId"
      | "recipeCount"
      | "recipes"
      | "submitRecipe"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "RecipeDeleted"
      | "RecipeSubmitted"
      | "RecipeUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteRecipe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedIngredient",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipeIngredients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipeSteps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecipeCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecipes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRecipe",
    values: [
      string,
      string,
      string,
      string[],
      BytesLike[],
      BytesLike[],
      BigNumberish[],
      string[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deleteRecipe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedIngredient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecipe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecipeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipeIngredients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipeSteps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecipeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecipes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recipeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRecipe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipeDeletedEvent {
  export type InputTuple = [recipeId: BigNumberish, chef: AddressLike];
  export type OutputTuple = [recipeId: bigint, chef: string];
  export interface OutputObject {
    recipeId: bigint;
    chef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipeSubmittedEvent {
  export type InputTuple = [
    recipeId: BigNumberish,
    chef: AddressLike,
    title: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recipeId: bigint,
    chef: string,
    title: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recipeId: bigint;
    chef: string;
    title: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipeUpdatedEvent {
  export type InputTuple = [recipeId: BigNumberish, chef: AddressLike];
  export type OutputTuple = [recipeId: bigint, chef: string];
  export interface OutputObject {
    recipeId: bigint;
    chef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedRecipeKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedRecipeKeeper;
  waitForDeployment(): Promise<this>;

  interface: EncryptedRecipeKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteRecipe: TypedContractMethod<
    [recipeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedIngredient: TypedContractMethod<
    [recipeId: BigNumberish, ingredientIndex: BigNumberish],
    [string],
    "view"
  >;

  getRecipe: TypedContractMethod<
    [recipeId: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        chef: string;
        title: string;
        description: string;
        prepTime: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getRecipeCount: TypedContractMethod<[], [bigint], "view">;

  getRecipeIngredients: TypedContractMethod<
    [recipeId: BigNumberish],
    [[string[], boolean[]] & { names: string[]; isEncrypted: boolean[] }],
    "view"
  >;

  getRecipeSteps: TypedContractMethod<
    [recipeId: BigNumberish],
    [
      [string[], boolean[]] & { descriptions: string[]; isEncrypted: boolean[] }
    ],
    "view"
  >;

  getUserRecipeCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserRecipes: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recipeCount: TypedContractMethod<[], [bigint], "view">;

  recipes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        chef: string;
        title: string;
        description: string;
        prepTime: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  submitRecipe: TypedContractMethod<
    [
      title: string,
      description: string,
      prepTime: string,
      ingredientNames: string[],
      encryptedAmounts: BytesLike[],
      amountProofs: BytesLike[],
      encryptedIngredientIndices: BigNumberish[],
      stepDescriptions: string[],
      encryptedStepIndices: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteRecipe"
  ): TypedContractMethod<[recipeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedIngredient"
  ): TypedContractMethod<
    [recipeId: BigNumberish, ingredientIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipe"
  ): TypedContractMethod<
    [recipeId: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        chef: string;
        title: string;
        description: string;
        prepTime: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecipeIngredients"
  ): TypedContractMethod<
    [recipeId: BigNumberish],
    [[string[], boolean[]] & { names: string[]; isEncrypted: boolean[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipeSteps"
  ): TypedContractMethod<
    [recipeId: BigNumberish],
    [
      [string[], boolean[]] & { descriptions: string[]; isEncrypted: boolean[] }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRecipeCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRecipes"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        chef: string;
        title: string;
        description: string;
        prepTime: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitRecipe"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      prepTime: string,
      ingredientNames: string[],
      encryptedAmounts: BytesLike[],
      amountProofs: BytesLike[],
      encryptedIngredientIndices: BigNumberish[],
      stepDescriptions: string[],
      encryptedStepIndices: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecipeDeleted"
  ): TypedContractEvent<
    RecipeDeletedEvent.InputTuple,
    RecipeDeletedEvent.OutputTuple,
    RecipeDeletedEvent.OutputObject
  >;
  getEvent(
    key: "RecipeSubmitted"
  ): TypedContractEvent<
    RecipeSubmittedEvent.InputTuple,
    RecipeSubmittedEvent.OutputTuple,
    RecipeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RecipeUpdated"
  ): TypedContractEvent<
    RecipeUpdatedEvent.InputTuple,
    RecipeUpdatedEvent.OutputTuple,
    RecipeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecipeDeleted(uint256,address)": TypedContractEvent<
      RecipeDeletedEvent.InputTuple,
      RecipeDeletedEvent.OutputTuple,
      RecipeDeletedEvent.OutputObject
    >;
    RecipeDeleted: TypedContractEvent<
      RecipeDeletedEvent.InputTuple,
      RecipeDeletedEvent.OutputTuple,
      RecipeDeletedEvent.OutputObject
    >;

    "RecipeSubmitted(uint256,address,string,uint256)": TypedContractEvent<
      RecipeSubmittedEvent.InputTuple,
      RecipeSubmittedEvent.OutputTuple,
      RecipeSubmittedEvent.OutputObject
    >;
    RecipeSubmitted: TypedContractEvent<
      RecipeSubmittedEvent.InputTuple,
      RecipeSubmittedEvent.OutputTuple,
      RecipeSubmittedEvent.OutputObject
    >;

    "RecipeUpdated(uint256,address)": TypedContractEvent<
      RecipeUpdatedEvent.InputTuple,
      RecipeUpdatedEvent.OutputTuple,
      RecipeUpdatedEvent.OutputObject
    >;
    RecipeUpdated: TypedContractEvent<
      RecipeUpdatedEvent.InputTuple,
      RecipeUpdatedEvent.OutputTuple,
      RecipeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
